# docker-compose.yml
services:
  blazor-init:
    build:
      context: .
      dockerfile: docker/Dockerfile.init
    volumes:
      - ./:/app

  blazor-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5151:80"
    volumes:
      - ./:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Add working directory environment variable
      - PROJECT_PATH=/app/Intrepion.ToDo.csproj

  blazor-prod:
    build:
      context: .
      dockerfile: docker/Dockerfile.publish
    ports:
      - "5151:80"
