# /docker-compose.yml

services:
  blazor-init:
    build:
      context: .
      dockerfile: docker/Dockerfile.init
    volumes:
      - ./:/app

  blazor-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5151:80"
    volumes:
      - ./:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PROJECT_PATH=/app/Intrepion.ToDo/Intrepion.ToDo.csproj

  blazor-test:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    entrypoint: ["dotnet"]
    command: ["test"]

  blazor-prod:
    build:
      context: .
      dockerfile: docker/Dockerfile.publish
    ports:
      - "5151:80"
