# fly.toml app configuration file generated for intrepion-to-do-web-blazor-delicate-mountain-8358 on 2024-08-08T01:45:08-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'intrepion-to-do-web-blazor-delicate-mountain-8358'
primary_region = 'sea'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
