@startuml

entity ToDoItem {
    Id : Guid
    --
    ' ToDoItemKeyCodePlaceholder
    --
    CreateDateTime : DateTime
    IsCompleted : bool
    ' ToDoItemPropertyCodePlaceholder
}

' EntityCodePlaceholder

' RelationshipCodePlaceholder

@enduml
