@startuml

entity ToDoItem {
    Id : Guid
    --
    ' ToDoItemKeyCodePlaceholder
    --
    IsCompleted : bool
    Ordering : int
    ' ToDoItemPropertyCodePlaceholder
}

' EntityCodePlaceholder

' RelationshipCodePlaceholder

@enduml
