@startuml

entity ToDoItem {
    Id : Guid
    --
    ApplicationUser : ApplicationUser
    ' ToDoItemKeyCodePlaceholder
    --
    DueDateTime : DateTime
    ' ToDoItemPropertyCodePlaceholder
}

' EntityCodePlaceholder

ToDoItem }o--o| ApplicationUser
' RelationshipCodePlaceholder

@enduml
